### ISSUE TITLE
Verbose logs no longer appear when running on Xcode 15 / iOS 17

### ISSUE THREAD

**Issue by jamesruston** [googleanalytics/google-tag-manager-ios-sdk#24]
According to the docs when the app is running in a simulator, GTM should automatically turn on verbose logging. After switching to Xcode 15 this no longer works. 

https://developers.google.com/tag-platform/tag-manager/ios/v5#debug_container
```
When you run your app in a simulator or in preview mode, Tag Manager automatically turns logging to verbose.
```

**Comment by ejiro-dp** [comment]
@jamesruston, was this issue fixed, or how did you go about it? I am experiencing the same thing; I can see any verbose logging.

**Comment by mpplslive** [comment]
@ejiro-dp @jamesruston Did you got it working? it seems that the issue is still there.
