### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by nataliagi-flutterint** [googleanalytics/google-tag-manager-ios-sdk#26]
**Question**

Hi,
At WWDC23 Apple announced that apps and SDKs that make use of "required reason" APIs and "Data Collection", "Tracking" will need to provide a privacy manifest.
Does GoogleTagManager need to include this manifest? 

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by ryang1428** [comment]
Hi we are also looking for this answer as well with the deadline fast approaching!

**Comment by LetsEvil** [comment]
Hi Team, Any update for the new release plan?

**Comment by bradwindy** [comment]
Also looking for an answer to this. I scanned the repo I work on that uses GTM with the following tool:
https://github.com/bradwindy/iOS17-Required-Reason-API-Scanner

And you use `NSFileModificationDate`, which requires you to include a privacy manifest explaining your use of this, as it falls under the `NSPrivacyAccessedAPICategoryFileTimestamp` API type.

**Comment by mattiacantalu** [comment]
Ehi @tsunghung  @htcgh any news about this topic?

**Comment by twprzybysz** [comment]
@tsunghung @htcgh
