### ISSUE TITLE
App Store submission failed for MinimumOSVersion

### ISSUE THREAD

**Issue by Oussama-Zakany** [googleanalytics/google-tag-manager-ios-sdk#28]
Hello,
I get the following issues while distributing my application to App Store (Xcode 15.3):

Asset validation failed
Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'XXX.app/Frameworks/GoogleAnalytics.framework' is ''. (ID: 8047b536-419e-4c19-8757-1d38ee7680a4)

Asset validation failed
Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'XXX.app/Frameworks/GoogleTagManager.framework' is ''. (ID: 0a8068ef-de8d-483d-bc4a-dfe6952addf0)

Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle XXX.app/Frameworks/GoogleAnalytics.framework is required. (ID: 21d8ffa1-3333-452a-91f4-c3f04c08f5f4)

Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle XXX.app/Frameworks/GoogleTagManager.framework is required. (ID: 990bf996-5a2a-44ce-830e-64bfb57719e6)

Asset validation failed
The bundle 'Payload/XXX.app/Frameworks/GoogleAnalytics.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: d4b4b2d7-6562-4d54-83e3-919d03b4709f)

Asset validation failed
The bundle 'Payload/XXX.app/Frameworks/GoogleTagManager.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: 4ec504d8-79c0-4715-97da-3bd8ca6b02bc)

Asset validation failed
Invalid Bundle. The bundle XXX.app/Frameworks/GoogleAnalytics.framework does not support the minimum OS Version specified in the Info.plist. (ID: 65cdd663-371f-4887-b5a3-0158a7ecf725)

Asset validation failed
Invalid Bundle. The bundle XXX.app/Frameworks/GoogleTagManager.framework does not support the minimum OS Version specified in the Info.plist. (ID: a3789d1e-9ce7-4c0c-ace3-80f8ce3ce474)

PS: I'm using Swift Package Manager

**Comment by garranhado** [comment]
Hi,

My team needs this to be fixed asap, we are blocked to submit an app to the App Store.

Thanks

```
Asset validation failed
Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'MyApp.app/Frameworks/GoogleAnalytics.framework' is ''. (ID: ac5da7f8-e508-41ba-bb2d-4854cf458afe)

Asset validation failed
Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'MyApp.app/Frameworks/GoogleTagManager.framework' is ''. (ID: 87316ff8-7132-4a38-b650-df7ba4dacd9c)

Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle MyApp.app/Frameworks/GoogleAnalytics.framework is required. (ID: 774b5f96-63de-4d71-ba58-295588870ab8)

Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle MyApp.app/Frameworks/GoogleTagManager.framework is required. (ID: 9b7f664c-ed79-45a6-a5bb-a6edb3c1f67d)

Asset validation failed
The bundle 'Payload/MyApp.app/Frameworks/GoogleAnalytics.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: 06f43fbc-40a6-4bdc-bc17-11ec2637c13d)

Asset validation failed
The bundle 'Payload/MyApp.app/Frameworks/GoogleTagManager.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: 3167d44e-c327-4d4b-b837-afb2091840b4)

Asset validation failed
Invalid Bundle. The bundle MyApp.app/Frameworks/GoogleAnalytics.framework does not support the minimum OS Version specified in the Info.plist. (ID: 5d569a5c-881c-45dc-852e-47f31843d2aa)

Asset validation failed
Invalid Bundle. The bundle MyApp.app/Frameworks/GoogleTagManager.framework does not support the minimum OS Version specified in the Info.plist. (ID: be13de3f-1b03-4200-a939-ee760da7d47b)
```

**Comment by darkCloud77** [comment]
This is causing my builds to get rejected from Apple during submission.  This needs to get fixed ASAP.

**Comment by tsunghung** [comment]
Please update GoogleTagManager to 7.4.5.
